// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMap.Data;

#nullable disable

namespace WebMap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902211213_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebMap.Models.Alan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Geometri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alanlar", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WebMap.Models.Fiber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaslangicId")
                        .HasColumnType("int");

                    b.Property<int>("BitisId")
                        .HasColumnType("int");

                    b.Property<string>("Guzergah")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fiberler");
                });

            modelBuilder.Entity("WebMap.Models.NetworkElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NetworkElements", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WebMap.Models.Konut", b =>
                {
                    b.HasBaseType("WebMap.Models.Alan");

                    b.Property<int>("BBKsayi")
                        .HasColumnType("int");

                    b.Property<int>("UAVTKod")
                        .HasColumnType("int");

                    b.ToTable("Konutlar", (string)null);
                });

            modelBuilder.Entity("WebMap.Models.Ticari", b =>
                {
                    b.HasBaseType("WebMap.Models.Alan");

                    b.Property<int>("IsyeriSayisi")
                        .HasColumnType("int");

                    b.Property<int>("UAVTKod")
                        .HasColumnType("int");

                    b.ToTable("Ticariler", (string)null);
                });

            modelBuilder.Entity("WebMap.Models.Kabin", b =>
                {
                    b.HasBaseType("WebMap.Models.NetworkElement");

                    b.Property<int>("BosPort")
                        .HasColumnType("int");

                    b.Property<int>("KabinKapasitesi")
                        .HasColumnType("int");

                    b.Property<string>("KabinTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Kabinler", (string)null);
                });

            modelBuilder.Entity("WebMap.Models.Menhol", b =>
                {
                    b.HasBaseType("WebMap.Models.NetworkElement");

                    b.Property<decimal>("Derinlik")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Menholler", (string)null);
                });

            modelBuilder.Entity("WebMap.Models.Konut", b =>
                {
                    b.HasOne("WebMap.Models.Alan", null)
                        .WithOne()
                        .HasForeignKey("WebMap.Models.Konut", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMap.Models.Ticari", b =>
                {
                    b.HasOne("WebMap.Models.Alan", null)
                        .WithOne()
                        .HasForeignKey("WebMap.Models.Ticari", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMap.Models.Kabin", b =>
                {
                    b.HasOne("WebMap.Models.NetworkElement", null)
                        .WithOne()
                        .HasForeignKey("WebMap.Models.Kabin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMap.Models.Menhol", b =>
                {
                    b.HasOne("WebMap.Models.NetworkElement", null)
                        .WithOne()
                        .HasForeignKey("WebMap.Models.Menhol", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
