// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMap.Data;

#nullable disable

namespace WebMap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908121955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebMap.Models.BirimMaliyet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Iscilik")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Malzeme")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NesneTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NesneTuru")
                        .IsUnique();

                    b.ToTable("BirimMaliyetler");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Iscilik = 2000m,
                            Malzeme = 3000m,
                            NesneTuru = "Menhol"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Iscilik = 4000m,
                            Malzeme = 6000m,
                            NesneTuru = "Kabin"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Iscilik = 20000m,
                            Malzeme = 30000m,
                            NesneTuru = "Santral"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Iscilik = 15m,
                            Malzeme = 25m,
                            NesneTuru = "Fiber"
                        });
                });

            modelBuilder.Entity("WebMap.Models.Fiber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaslangicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BitisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Guzergah")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Fiberler");
                });

            modelBuilder.Entity("WebMap.Models.Konut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BBKsayi")
                        .HasColumnType("int");

                    b.Property<string>("Geometri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UAVTKod")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Konutlar");
                });

            modelBuilder.Entity("WebMap.Models.NetworkElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("NetworkElements", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WebMap.Models.Proje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Geometri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("WebMap.Models.Santral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BosPort")
                        .HasColumnType("int");

                    b.Property<string>("Geometri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Santraller");
                });

            modelBuilder.Entity("WebMap.Models.Kabin", b =>
                {
                    b.HasBaseType("WebMap.Models.NetworkElement");

                    b.Property<int>("BosPort")
                        .HasColumnType("int");

                    b.Property<int>("KabinKapasitesi")
                        .HasColumnType("int");

                    b.Property<string>("KabinTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Kabinler", (string)null);
                });

            modelBuilder.Entity("WebMap.Models.Menhol", b =>
                {
                    b.HasBaseType("WebMap.Models.NetworkElement");

                    b.Property<decimal>("Derinlik")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Menholler", (string)null);
                });

            modelBuilder.Entity("WebMap.Models.Kabin", b =>
                {
                    b.HasOne("WebMap.Models.NetworkElement", null)
                        .WithOne()
                        .HasForeignKey("WebMap.Models.Kabin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMap.Models.Menhol", b =>
                {
                    b.HasOne("WebMap.Models.NetworkElement", null)
                        .WithOne()
                        .HasForeignKey("WebMap.Models.Menhol", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
